### ISSUE TITLE
The boiler issue

### ISSUE THREAD

**Issue by Mrtrainman** [Layers-of-Railways/Railway#428] opened 2024-04-09 15:28 UTC
### Describe the Bug

when i place a block front of a boiler it somehow you can see the inside but when i place a copycat you cannot see threw

### Reproduction Steps

1.place block and can see threw
2.copycats cannot see threw
3.
...

### Expected Result

when i was building any steam train and place a block front of a boiler and can see threw but if i use a copycat it cannot see threw

### Screenshots and Videos

![2024-04-09_23 23 27](https://github.com/Layers-of-Railways/Railway/assets/153827522/c014232c-462b-44a3-8e46-583b8d732a62)

### Crash Report or Log

none

### Operating System

windows 10

### Mod Version

1.6.1

### Create Mod Version

0.5.1f

### Minecraft Version

1.20.1

### ModLoader and Version

forge-43.2.21

### Other Mods

none of them do this problem just this mod

### Additional Context

none

**Comment by Mrtrainman** [comment] 2024-04-09 15:29
please fix this problem

**Comment by IThundxr** [comment] 2024-04-09 15:33
Try installing embeddium

**Comment by IThundxr** [comment] 2024-04-09 15:33
Sorry, closed by accident

**Comment by IThundxr** [comment] 2024-04-12 22:58
cant reproduce, if your using rubidium this is likely caused by that

**Closed as completed by IThundxr** 2024-04-12 22:58 UTC
Labels: version: 1.20, type: bug
