### ISSUE TITLE
Crash when pondering conductor cap

### ISSUE THREAD

**Issue by Jammssangees** [Layers-of-Railways/Railway#191] opened 2023-07-23 21:54 UTC
Every time i load the second part of the conductor cap ponder, my game crashes
[crash-2023-07-23_23.41.47-fml.txt](https://github.com/Layers-of-Railways/Railway/files/12140032/crash-2023-07-23_23.41.47-fml.txt)

**Comment by techno-sam** [comment] 2023-07-24 03:24
Downgrade to Create 0.5.1b

**Comment by Jammssangees** [comment] 2023-07-24 14:18
still crashes with 0.5.1.b
[crash-2023-07-24_16.17.12-client.txt](https://github.com/Layers-of-Railways/Railway/files/12146858/crash-2023-07-24_16.17.12-client.txt)

**Comment by techno-sam** [comment] 2023-08-02 02:48
duplicate of #183

**Closed as completed by techno-sam** 2023-08-02 02:48 UTC
