### ISSUE TITLE
[Crash] updateWithAllFixers(DataFixesInternalsImpl.java:69)

### ISSUE THREAD

**Issue by purejosh** [Layers-of-Railways/Railway#243] opened 2023-09-03 03:08 UTC
### Describe the Bug

Server crashes when loading some create blocks/items in the world, but is fine around some create contraptions. If I don't load the chunks with these machines in it, it doesn't crash. 

Spark report: https://spark.lucko.me/S9vE1ygYBU
Crash log: https://gist.github.com/purejosh/231714d0e9af2e633eadfeb8baa20365

### Reproduction Steps

1. Install Create: Steam 'n' Rails with the mods in my logs
2. Load certain create machines (unknown at this time)
3. Server will crash. 

### Expected Result

Not crash. 

### Crash Report or Log

latest.log https://gist.github.com/purejosh/badf968766593de62e796ddbf893081c

### Operating System

n/a

### Mod Version

1.5.0

### Create Mod Version

0.5.1d

### Minecraft Version

1.19.2

### ModLoader and Version

Fabric 0.14.22

### Other Mods

See latest.log

**Comment by MentoskaPraha** [comment] 2023-09-06 20:21
According to the Discord FAQ channel this is caused by Farmer's Delight Fabric. Beyond that I've got no clue, I'll try to look into it.

**Comment by IThundxr** [comment] 2023-09-06 20:41
@purejosh could you try to replicate this without farmers delight?

**Comment by IThundxr** [comment] 2023-09-06 20:43
also could you try with disabling the data fixer in the steam n rails config file?

**Comment by IThundxr** [comment] 2023-09-09 11:33
Can you try disabling the data fixer in steam 'n' rails config?

**Comment by purejosh** [comment] 2023-09-11 05:47
I will attempt to address this next week, but this is a production server. I may be slow to test. Thanks!

**Comment by IThundxr** [comment] 2023-09-17 12:43
Closing since this looks like its just your server lagging to hard and then crashing change the watchdog timeout in server properties to 0 and it shouldnt crash anymore

**Closed as completed by IThundxr** 2023-09-17 12:43 UTC
Labels: version: 1.19, type: bug

**Comment by purejosh** [comment] 2023-09-17 12:48
It runs on a 5950x, so that's definitely not it. Watchdog is already set to 60 seconds. If a tick can't complete in 60 seconds, there's no hope. 

It's the combination of mods.

**Comment by IThundxr** [comment] 2023-09-17 12:51
> It runs on a 5950x, so that's definitely not it. Watchdog is already set to 60 seconds. If a tick can't complete in 60 seconds, there's no hope.
> 
> It's the combination of mods.

Not always once again your issue here is the datafixer which causes lag and thats a base minecraft feature that mods can use and we do that once you turn off our datafixer it should fix the lag from our side but any other datafixers will still cause lag
