### ISSUE TITLE
Resource Pack not compatible with 1.20.1

### ISSUE THREAD

**Issue by MrTwitchnAnubis** [Layers-of-Railways/Railway#303] opened 2023-11-01 06:34 UTC
### Describe the Bug

So trying to get the resource packs for Create: Steam ‘n’ Rails, however both Steam 'n' Rails Green Signals and Legacy Semaphore resource packs are not wanting to be compatible and when viewing the information for each resource pack.mcmeta file is saying that the pack_format is set to 15 which correlates to Minecraft game versions of 1.20 - 1.20.1

Can anyone offer any suggestions?

### Reproduction Steps

1. Just loading up Minecraft into the main menu

### Expected Result

For the resource packs to be compatible

### Screenshots and Videos

![Resource Packs 1](https://github.com/Layers-of-Railways/Railway/assets/139184562/ad18efe2-8d11-4849-aa4b-cddc33614336)
![Resource Packs 2](https://github.com/Layers-of-Railways/Railway/assets/139184562/05d2216a-0047-44c4-ac30-c866d254254c)

### Operating System

Windows 10

### Mod Version

1.5.2

### Create Mod Version

0.5.1e

### Minecraft Version

1.20.1

### ModLoader and Version

Forge 47.2.1

**Comment by IThundxr** [comment] 2023-11-01 11:29
Ah this is a easy fix just need to bump the pack versions

**Comment by MrTwitchnAnubis** [comment] 2023-11-04 01:48
> Ah this is a easy fix just need to bump the pack versions

that is what I thought I did, by going right clicking on it and opening it in WinRAR Archiver and editing the pack.mcmeta in the resource packs to match the game version of 1.20.1 which would be 15, but even doing that is still saying that it is not compatible
![steps 1 to 3](https://github.com/Layers-of-Railways/Railway/assets/139184562/58ed456e-8330-4f03-a1a7-6f50a74f3efb)
![step 4](https://github.com/Layers-of-Railways/Railway/assets/139184562/29ab834c-fbdb-4ee3-ac4e-90102a406b69)
![step 5](https://github.com/Layers-of-Railways/Railway/assets/139184562/b41fae8b-a6c6-4c98-8b5e-a3cb0685cf54)
![step 6](https://github.com/Layers-of-Railways/Railway/assets/139184562/c752e0b1-35ce-4808-8dee-04f2eefce5be)

**Comment by MrTwitchnAnubis** [comment] 2023-11-04 01:49
> Ah this is a easy fix just need to bump the pack versions

if i am missing something can you please tell me what that is

**Comment by IThundxr** [comment] 2023-11-11 03:34
Hm not sure why this is happening it should be correct, can you try with just snr & create and see if it still happens?

**Comment by IThundxr** [comment] 2023-11-20 01:45
closing since cant reproduce with just snr & create

**Closed as completed by IThundxr** 2023-11-20 01:45 UTC
Labels: version: 1.20, type: bug, status: unable to reproduce
