### ISSUE TITLE
instant crash when making a T junction

### ISSUE THREAD

**Issue by pfebvay** [Layers-of-Railways/Railway#14] opened 2022-11-29 18:36 UTC
as the title say, my game crashed as soon as i placed the third track with 3 semaphore on top of each other, i know the 3rd one don't do anything but wanted to try some stuffs, now i can come back to the spot and can't reproduce that crash, but i still wanted to say it ! (thanks muri !)
anyway here the crash log, and as you can see there a lot of other mods so it "could" be those, but since i'm unsure i'm here !
thanks for your really great mod !
[crash-2022-11-27_18.19.07-client.txt](https://github.com/Layers-of-Railways/Railway/files/10116099/crash-2022-11-27_18.19.07-client.txt)

**Comment by techno-sam** [comment] 2022-12-02 06:55
Thank you. If you could include a screenshot of the block setup that crashed the game (even if you can't reproduce it) that would be helpful

**Comment by techno-sam** [comment] 2022-12-02 06:57
However, reading your crashlog, that is a known bug, and should (hopefully) be fixed in the next release (1.0.2) which should be out in the next week or so.

**Closed as completed** 2022-12-03 23:26 UTC
