### ISSUE TITLE
1.19.2 fabric server is crashing while client works perfectly fine

### ISSUE THREAD

**Issue by ghasto69** [Layers-of-Railways/Railway#106] opened 2023-04-24 14:48 UTC
I am using steam and rails 1.19.2 fabric loose dependencies jar and the client launches perfectly fine and I can load a world and use the mod but trying to use the mod on a server causes it to crash.

**Comment by Blizzor** [comment] 2023-04-24 16:20
Here are more Information about the problem:
This is the error message:
`Mod 'Create: Steam 'n Rails' (railways) 1.2.2+fabric-mc1.19.2 requires version 0.5.0.i-1000+1.19.2 of mod 'Create' (create), but only the wrong version is present: 0.5.0.i-991+1.19.2!`
...which means, the requirements should be changed.

Thank you for the hopefully fast update!

**Comment by gittibene** [comment] 2023-04-24 16:50
Even with fixed requirements the mod does not work on the server, client is fine. Here is the actual error:

`[main/ERROR]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'railways'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[fabric-loader-0.14.19.jar:?]
	at net.minecraft.server.Main.main(Main.java:101) [server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462) [fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.14.19.jar:?]
Caused by: java.lang.NoClassDefFoundError: com/jozufozu/flywheel/core/PartialModel
	at com.simibubi.create.AllBlockPartials.block(AllBlockPartials.java:186) ~[create-fabric-0.5.0.i-991+1.19.2.jar:?]
	at com.simibubi.create.AllBlockPartials.<clinit>(AllBlockPartials.java:19) ~[create-fabric-0.5.0.i-991+1.19.2.jar:?]
	at com.railwayteam.railways.track_api.TrackMaterial$TrackModelHolder.<clinit>(TrackMaterial.java:250) ~[Steam_Rails-1.2.2+fabric-mc1.19.2.jar:?]
	at com.railwayteam.railways.track_api.TrackMaterialFactory.setBuiltin(TrackMaterialFactory.java:46) ~[Steam_Rails-1.2.2+fabric-mc1.19.2.jar:?]
	at com.railwayteam.railways.track_api.TrackMaterial.<clinit>(TrackMaterial.java:37) ~[Steam_Rails-1.2.2+fabric-mc1.19.2.jar:?]
	at com.railwayteam.railways.registry.CRItems.<clinit>(CRItems.java:113) ~[Steam_Rails-1.2.2+fabric-mc1.19.2.jar:?]
	at com.railwayteam.railways.ModSetup.register(ModSetup.java:7) ~[Steam_Rails-1.2.2+fabric-mc1.19.2.jar:?]
	at com.railwayteam.railways.Railways.init(Railways.java:43) ~[Steam_Rails-1.2.2+fabric-mc1.19.2.jar:?]
	at com.railwayteam.railways.fabric.RailwaysImpl.onInitialize(RailwaysImpl.java:22) ~[Steam_Rails-1.2.2+fabric-mc1.19.2.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.19.jar:?]
	... 7 more
Caused by: java.lang.ClassNotFoundException: com.jozufozu.flywheel.core.PartialModel
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.19.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at com.simibubi.create.AllBlockPartials.block(AllBlockPartials.java:186) ~[create-fabric-0.5.0.i-991+1.19.2.jar:?]
	at com.simibubi.create.AllBlockPartials.<clinit>(AllBlockPartials.java:19) ~[create-fabric-0.5.0.i-991+1.19.2.jar:?]
	at com.railwayteam.railways.track_api.TrackMaterial$TrackModelHolder.<clinit>(TrackMaterial.java:250) ~[Steam_Rails-1.2.2+fabric-mc1.19.2.jar:?]
	at com.railwayteam.railways.track_api.TrackMaterialFactory.setBuiltin(TrackMaterialFactory.java:46) ~[Steam_Rails-1.2.2+fabric-mc1.19.2.jar:?]
	at com.railwayteam.railways.track_api.TrackMaterial.<clinit>(TrackMaterial.java:37) ~[Steam_Rails-1.2.2+fabric-mc1.19.2.jar:?]
	at com.railwayteam.railways.registry.CRItems.<clinit>(CRItems.java:113) ~[Steam_Rails-1.2.2+fabric-mc1.19.2.jar:?]
	at com.railwayteam.railways.ModSetup.register(ModSetup.java:7) ~[Steam_Rails-1.2.2+fabric-mc1.19.2.jar:?]
	at com.railwayteam.railways.Railways.init(Railways.java:43) ~[Steam_Rails-1.2.2+fabric-mc1.19.2.jar:?]
	at com.railwayteam.railways.fabric.RailwaysImpl.onInitialize(RailwaysImpl.java:22) ~[Steam_Rails-1.2.2+fabric-mc1.19.2.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.19.jar:?]
	... 7 more
`

**Comment by ghasto69** [comment] 2023-04-25 00:07
Yeah, that’s exactly what I meant at the start.

**Comment by techno-sam** [comment] 2023-04-25 00:11
looks like TrackMaterial registration needs some client guards

**Comment by techno-sam** [comment] 2023-04-26 03:14
fixed in 1.2.3

**Closed as completed by techno-sam** 2023-04-26 03:14 UTC
