### ISSUE TITLE
Toolboxes on Conductors Broken

### ISSUE THREAD

**Issue by thegrandslam2002** [Layers-of-Railways/Railway#90] opened 2023-03-31 03:47 UTC
Tested on most recent release. Giving a toolbox to a conductor causes the open toolbox hotkey to display a full wheel of toolboxes, even when only one exists. Even after the conductor dies, this effect persists in the area where it was.

**Comment by techno-sam** [comment] 2023-04-03 17:06
Going to need more info here - what version of Steam 'n Rails, Create, and Minecraft are you using?

**Comment by thegrandslam2002** [comment] 2023-04-03 19:43
MC 1.18.2, most recent release of Create and Steam 'n' Rails

**Comment by techno-sam** [comment] 2023-04-26 03:15
Please confirm this is still an issue on 1.2.3

**Comment by techno-sam** [comment] 2023-06-11 22:06
Unable to reproduce and haven't received a response, closing

**Closed as not planned by techno-sam** 2023-06-11 22:06 UTC
