### ISSUE TITLE
Smoke Stacks on assembled contraptions do not produce smoke if there is a block ontop

### ISSUE THREAD

**Issue by SabrCat** [Layers-of-Railways/Railway#292] opened 2023-10-10 17:03 UTC
### Describe the Bug

As the title says, if one has a smoke stack with a block on top, even just a slab, it stops producing smoke even in assembled form. I have also intermittently observed that a smoke stack can occasionally get stuck producing no smoke even after disassembly. Sometimes the smoke stack will spit out a few more smoke particles after assembling the contraption, and then cease smoking. 

### Reproduction Steps

https://github.com/Layers-of-Railways/Railway/assets/56313836/cec489e2-a05a-4384-82c0-f3134167e52d

### Expected Result

There should be smoke when the train is assembled

### Screenshots and Videos

see above in reproduction steps

### Operating System

Windows 10

### Mod Version

1.5.0

### Create Mod Version

0.5.1c

### Minecraft Version

1.19.2

### ModLoader and Version

Fabric 0.14.22

### Other Mods

Custom Modpack based on Fabulously Optimized

**Comment by techno-sam** [comment] 2023-12-28 19:34
I am not able to reproduce this issue. I suspect that you may be confused by the fact that smoke emission on trains is speed-dependent, and so when you assemble a train, the frequency of smoke goes down significantly

**Comment by IThundxr** [comment] 2024-04-14 15:53
fixed by 1.6.0 with new particles

**Closed as completed by IThundxr** 2024-04-14 15:53 UTC
Labels: version: 1.19, type: bug, status: unable to reproduce
