### ISSUE TITLE
Game crashes when using radial menu with Steam_Rails-1.5.0+fabric-mc1.19.2-build.14

### ISSUE THREAD

**Issue by Halex000** [Layers-of-Railways/Railway#239] opened 2023-08-28 19:25 UTC
### Describe the Bug

When opening the radial menu to select a bogey type, when the cursor is hovered over any of the options in the menu the game crashes. The game will not crash until a menu item is hovered over however.
[crash-2023-08-28_15.01.06-client.txt](https://github.com/Layers-of-Railways/Railway/files/12457593/crash-2023-08-28_15.01.06-client.txt)
[latest.log](https://github.com/Layers-of-Railways/Railway/files/12457594/latest.log)

### Reproduction Steps

1. Hold a train casing and open the radial menu
2. Move mouse to hover over the menu

### Expected Result

The game should not crash

### Crash Report or Log

https://pastebin.com/6JqZbYDz

### Operating System

Windows 10

### Mod Version

1.5.0

### Create Mod Version

0.5.1c

### Minecraft Version

1.19.2

### ModLoader and Version

Fabric 0.14.22

### Other Mods

accurateblockplacement: Accurate Block Placement 1.0.15
advdebug: Advancements Debug 2.3.0
applecrates: Apple Crates 2.8.5
appleskin: AppleSkin 2.4.1+mc1.19
architects_palette: Architect's Palette Fabric 3.0.0
architectury: Architectury 6.5.85
attributefix: AttributeFix 17.2.6
audioplayer: AudioPlayer 1.19.2-1.4.5
bcc: BetterCompatibilityChecker 2.0.2-build.16+mc1.19.1
bclib: BCLib 2.1.7
beaconoverhaul: Beacon Overhaul 1.7.3+1.19.2
beautify: Beautify 1.1.1+fabric-1.19.2
bee_info: More Bee info  1.1.2
beekeeperhut: Friends&Foes - Beekeeper Hut 1.2.0
betterend: Better End 2.1.6
betterf3: BetterF3 4.0.0
bettermounthud: Better Mount HUD 1.2.0
betterpingdisplay: Better Ping Display 1.1.1
betterthirdperson: Better Third Person 1.9.0
bettertridents: Better Tridents 4.0.2
biomemakeover: Biome Makeover 1.19.2-1.6.4
block_limit_fix: Block Limit Fix 1.0.3-fabric
blockus: Blockus 2.5.10+1.19.2
blur: Blur (Fabric) 2.6.0
bookshelf: Bookshelf 16.3.20
brazier: Brazier 5.0.0
brewinandchewin: Brewin And Chewin fabric-2.1.5+1.19.2
bwncr: Bad Wither No Cookie Reloaded 3.14.1
byg: Oh The Biomes You'll Go 2.0.0.13
cccbridge: CC:C Bridge v1.5.1-fabric
charm: Charm 4.4.4
charmofundying: Charm of Undying 6.2.0+1.19.2
chefsdelight: Chef's Delight 1.0.3-fabric-1.19.2
chipped: Chipped 2.1.4
citresewn: CIT Resewn 1.1.2+1.19.2
cleancut: CleanCut 1.19.2-5.1-fabric
cloth-config: Cloth Config v8 8.2.88
clumps: Clumps 9.0.0+14
collective: Collective 6.53
colorfulazaleas: Colorful Azaleas 2.3.1
comforts: Comforts 6.0.4+1.19.2
computercraft: CC: Restitched 1.101.2
configured: Configured 2.0.0
connectiblechains: Connectible Chains 2.1.4+1.19.2
connectivity: Connectivity Mod 1.19.2-4.2
controlling: Controlling For Fabric 10.0+7
cosmetic-armor: Cosmetic Armor 1.4.2
crafttweaker: CraftTweaker 10.1.45
crawl: Crawl 0.11.1
create: Create 0.5.1-c-build.1160+mc1.19.2
create_enchantment_industry: Create Enchantment Industry 1.0.1
create_so: Create: Sandpaper Overhaul 1.5+fabric-1.19.2
createaddition: Create Crafts & Additions 20230723a
createbigcannons: Create Big Cannons 0.5.2-nightly-77aa315
createdeco: Create Deco 1.3.3-1.19.2
creategoggles: Create Goggles 0.5.5.c
creativecore: CreativeCore (Fabric) 2.9.3
ctm: ConnectedTexturesMod for Fabric 1.0.1+1.19
culturaldelights: Cultural Delights Fabric 0.14.9+1.19.2
customizableelytra: Customizable Elytra 1.6.4-1.19
decorative_blocks: Decorative Blocks 3.0.0
deeperdarker: Deeper and Darker 1.1.6
delightfulcreators: Delightful Creators 1.1.7
discontinuous_beacon_beams: Discontinuous Beacon Beams 1.1.7
doapi: Lets Do Api 1.1.0
dummmmmmy: MmmMmmMmmMmm 1.19.2-1.7.1
easyanvils: Easy Anvils 4.0.11
easymagic: Easy Magic 4.3.3
easyshulkerboxes: Easy Shulker Boxes 4.4.1
ecologics: Ecologics 2.1.11
effective: Effective 1.4
enchantedshulkers: Enchanted Shulkers 1.0.4
enchdesc: EnchantmentDescriptions 13.0.14
enchlevel-langpatch: Enchantment Level Language Patch 2.0.2
entity_texture_features: Entity Texture Features 4.3.3
essential: Essential 13437+deploy-staging+gd2fc09762
essential-container: essential-container 1.0.0
everycomp: Every Compat 1.19.2-2.5.1
expandability: ExpandAbility 7.0.0
expandeddelight: Expanded Delight 0.2.5.2
expandedstorage: Expanded Storage 8.3.4
fabric-api: Fabric API 0.76.0+1.19.2
fabric-language-kotlin: Fabric Language Kotlin 1.9.5+kotlin.1.8.22
fabric-ofcapes: OF Capes 2.0.0
fabricloader: Fabric Loader 0.14.22
fallingleaves: Falling Leaves 1.13.0+1.19.2
farmersdelight: Farmer's Delight 1.19.2-1.3.10
farsight: Farsight Mod 1.19-2.4
faux-custom-entity-data: Faux-Custom-Entity-Data 2.0.2
ferritecore: FerriteCore 5.0.3
forgeconfigapiport: Forge Config API Port 4.2.11
frame: Frame 0.26.1+1.19-fabric
friendsandfoes: Friends&Foes 1.8.2
galosphere: Galosphere 1.19.2-1.2.2
geckolib3: Geckolib 3.1.40
goodall: Goodall 1.2.0
handcrafted: Handcrafted 2.0.6
iceberg: Iceberg 1.0.46
immersive_weathering: Immersive Weathering 1.19.2-1.2.9
indium: Indium 1.0.9+mc1.19.2
infinitybuttons: Infinity Buttons 3.1.0-mc1.19.2
ingredient-extension-api: Ingredient Extension API 3.0.6
jade: Jade 8.7.3
jadeaddons: Jade Addons 3.2.0
java: OpenJDK 64-Bit Server VM 17
konkrete: Konkrete 1.6.1
kubejs: KubeJS 1902.6.0-build.142
lambdynlights: LambDynamicLights 2.2.0+1.19.2
langpatch-conf4: Enchantment Level Language Patch Config 4.0.0
lazydfu: LazyDFU 0.1.3
led: Light Emitting Diode 1.3.0
libipn: libIPN 3.0.2
lithium: Lithium 0.11.1
luggage: Luggage 1.19-1.5.2
mcwdoors: Macaw's Doors 1.0.8
mcwtrpdoors: Macaw's Trapdoors 1.1.1
mcwwindows: Macaw's Windows 2.1.2
meadow: Meadow 1.2.0
measurements: Measurements 1.3.1
megaparrot: Megaparrot 1.0.7-1.19.2
memoryusagescreen: Memory Usage Screen 1.6
minecraft: Minecraft 1.19.2
minegate-moreblocks: MineGate · MoreBlocks 1.2.5
modelfix: Model Gap Fix 1.8
modmenu: Mod Menu 4.1.2
moonlight: Moonlight 1.19.2-2.2.44
mousetweaks: Mouse Tweaks 2.22
mousewheelie: Mouse Wheelie 1.10.7+mc1.19.2
naturescompass: Nature's Compass 1.19.2-2.1.0-fabric
nethersdelight: Nether's Delight 1.0.1
no_more_purple: No More Purple 1.0.1
notenoughcrashes: Not Enough Crashes 4.2.1+1.19.2
onsoulfire: On Soul Fire 1.19-2
org_jetbrains_annotations: annotations 13.0
owo: oωo 0.8.5+1.19
patchouli: Patchouli 1.19.2-77-FABRIC
pathunderfencegates: Path Under Fence Gates 1.3.0
plushies: Plushie Mod 1.2
polymorph: Polymorph 0.46.1+1.19.2
ponderjs: PonderJS 1.1.11
puzzleslib: Puzzles Lib 4.4.0
quickshulker: Quick Shulker 1.3.9-1.19
railways: Create: Steam 'n' Rails 1.5.0+fabric-mc1.19.2-build.14
reeses-sodium-options: Reese's Sodium Options 1.4.9+mc1.19.2-build.67
resourcefullib: Resourceful Lib 1.1.24
respitecreators: Respite Creators 1.2.0
rhino: Rhino 1902.2.2-build.268
rottencreatures: Rotten Creatures 1.0.1
roughly_enough_loot_tables: Roughly Enough Loot Tables 1.19-1.0
roughly_enough_trades: Roughly Enough Trades 1.19-1.0
roughlyenoughitems: Roughly Enough Items 9.1.615
roughlyenoughprofessions: Roughly Enough Professions 1.1.4
roughlyenoughresources: Roughly Enough Resources 2.6.0
satin: Satin 1.9.0
showmeyourskin: Show Me Your Skin! 1.6.3+1.19.2
shulkerboxtooltip: Shulker Box Tooltip 3.2.2+1.19.2
skinlayers: 3d Skin Layers 1.5.2-mc1.19.1
skylorlib: SkyLib 1.5.1
sliceanddice: Create Slice & Dice 2.3.1
smoothboot: Smooth Boot 1.19-1.7.1
smoothchunk: Smooth chunk save Mod 1.19.1-2.0
sodium: Sodium 0.4.4+build.18
sodium-extra: Sodium Extra 0.4.16+mc1.19.2-build.90
starlight: Starlight 1.1.1+fabric.ae22326
statement: Statement 4.2.5+1.14.4-1.19.3
steel: Steel 1.3.1+1.19.2
strawstatues: Straw Statues 4.0.10
structory: Structory 1.0.1
supplementaries: Supplementaries 1.19.2-2.3.17
swampier_swamps: Swampier Swamps 1.19-1.2.1
terrablender: TerraBlender 2.0.1.136
thonkutil: ThonkUtil 2.15.4+1.19
tipthescales: Tip The Scales 6.0.10
toolstats: ToolStats 12.0.2
trade_cycling: Trade Cycling 1.19.2-1.0.5
tradingpost: Trading Post 4.2.0
transparent: Transparent 5.1.2
trinkets: Trinkets 3.4.2
twigs: Twigs 3.0.0
universalcraft: UniversalCraft 277
v_slab_compat: v_slab_compat 1.19.2-1.4
vigilance: Vigilance 284
villagersplus: Villagers Plus 1.9
vinery: Vinery 1.3.9
visuality: Visuality 0.5.6
voicechat: Simple Voice Chat 1.19.2-2.4.10
wiredredstone: Wired Redstone 0.4.19+1.19.2
wondrouswilds: Wondrous Wilds 1.19.2-1.1.6
worldedit: WorldEdit 7.2.12+6240-87f4ae1
xaerominimap: Xaero's Minimap 23.4.4
xaeroworldmap: Xaero's World Map 1.30.3
xercapaint: Joy of Painting fabric-1.19.2-1.0.2
xlpackets: XLPackets 1.19.2-4
yet-another-config-lib: YetAnotherConfigLib 2.2.0-for-1.19.2

### Additional Context

In the Mod Version drop down menu, 1.5.0 is not an option. I used that version of Railway to reproduce the bug, not 1.4.3.

I have a download for the modpack here:
https://www.mediafire.com/file/3k4fzf0syqhag00/Clockwork_S2_Modpack_v1.16.zip/file
Create and Steam and Rails will both have to be updated to 1.5.1c and 1.5.0 respectively in that download however.

**Comment by Halex000** [comment] 2023-08-28 21:01
I did a binary search to narrow down the mods and managed to identify that the crash is some sort of incompatibility with farmer's delight. By the end of my binary search this was the remaining mods that I could use to recreate this issue. Still with fabric 1.14.22
![Capture](https://github.com/Layers-of-Railways/Railway/assets/95841600/45a1f0a9-1e6a-41cb-8105-40c637eb2e17)
[latest.log](https://github.com/Layers-of-Railways/Railway/files/12458242/latest.log)
[crash-2023-08-28_17.06.24-client.txt](https://github.com/Layers-of-Railways/Railway/files/12458238/crash-2023-08-28_17.06.24-client.txt)

**Comment by jonathansharpe** [comment] 2023-08-28 23:07
i am also experiencing this bug, also with those four mods (and many more)

**Comment by ICHTLAY** [comment] 2023-08-30 05:27
@Halex000 @jonathansharpe This version of Steam n Rails doesnt work with Create 0.5.1c, downgrade Create to 0.5.1b. Also I see you have Create Enchanted Industry, probably you will need to downgrade this mod along with Create

**Comment by UnitingMatrixXCV** [comment] 2023-08-30 05:36
> @Halex000 @jonathansharpe This version of Steam n Rails doesnt work with Create 0.5.1c, downgrade Create to 0.5.1b. Also I see you have Create Enchanted Industry, probably you will need to downgrade this mod along with Create

Steam n Rails 1.5.0 was made FOR Create 0.5.1c .. SnR 1.4.x doesn't work on 0.5.1c

**Comment by Halex000** [comment] 2023-08-30 20:55
> @Halex000 @jonathansharpe This version of Steam n Rails doesnt work with Create 0.5.1c, downgrade Create to 0.5.1b. Also I see you have Create Enchanted Industry, probably you will need to downgrade this mod along with Create

Like Matrix said, that is incorrect. Steam n Rails 1.5.0 is designed to work on and only on Create 0.5.1c. If I wanted to use an older version of Steam n Rails then I would need to downgrade Create. This information is all in the changelog channel in the Steam n Rails discord server.

**Comment by IThundxr** [comment] 2023-08-30 21:13
Could you make a issue request on farmers delights GitHub?

**Comment by Aiq0** [comment] 2023-09-09 13:49
Just small addition, I am able to reproduce crash when I also move mouse (hovering some option is not needed).

**Comment by IThundxr** [comment] 2023-09-09 13:50
> Just small addition, I am only able to reproduce crash when I try to do something with the radial menu (for example: move mouse), opening radial menu itself does not cause crash.

Yeah sadly it's out of our hands if it was something wrong in steam n rails I could've fixed it and released a patched version however it's in farmers delight fabric so all you can really do it wait for them to fix it

**Comment by IThundxr** [comment] 2023-09-09 15:24
Closing since its already being tracked at farmers delights repo

**Closed as completed by IThundxr** 2023-09-09 15:24 UTC
Labels: version: 1.19, type: bug, type: crash, area: compatibility
