### ISSUE TITLE
Train Coupler

### ISSUE THREAD

**Issue by MarobsKoco** [Layers-of-Railways/Railway#80] opened 2023-02-26 09:54 UTC
Hello,

I do have problem with the train coupler. I made a train with 1 card, then i decoupled it, Now the problem, It wont couple again. When i look at the info ui, it seem that it wont recognize the first or the second train.

Minecraft: 1.18.2
Forge: 40.2.0
Steam 'n rail: 1.1.1

Is there some thing i did wrong, or is this a bug. Cant seem to couple them again. Tryed every thing, even move the train and car, but no luck.

Greets Marobs

![2023-02-26_10 52 00](https://user-images.githubusercontent.com/64714142/221403705-c4c8b5d1-e8ec-42cd-9180-1f7754d4674c.png)
![2023-02-26_10 52 08](https://user-images.githubusercontent.com/64714142/221403707-2f2e032f-7a55-400a-8de1-0c7974726d1d.png)

**Comment by MarobsKoco** [comment] 2023-02-26 11:12
I solved it for now. the problem was, the trains where to big, and the space between train boggies was 7 block as u can see on the picture. I made both trains 1 block shorter so it has 5 block between, and it solved the problem. I don't know why u even can go up to ten block if it not even works. Greets Marobs

**Comment by techno-sam** [comment] 2023-03-12 20:19
Unable to reproduce this bug. Closing for now.

**Closed as completed by techno-sam** 2023-03-12 20:19 UTC
