### ISSUE TITLE
Compatibility issue with Quark and JEI

### ISSUE THREAD

**Issue by ghost** [Layers-of-Railways/Railway#183] opened 2023-07-17 12:19 UTC
The game will crash if you try to ponder about conductor's cap in the second scene when JEI and Quark are installed simultaneously
[crash-2023-07-17_20.16.22-client.txt](https://github.com/Layers-of-Railways/Railway/files/12069073/crash-2023-07-17_20.16.22-client.txt)
[latest.log](https://github.com/Layers-of-Railways/Railway/files/12069070/latest.log)
modlist:
AutoRegLib-1.8.2-55
Quark-3.4-405
jei-1.19.2-forge-11.6.0.1016
create-1.19.2-0.5.1.b
Steam_Rails-1.4.3+forge-mc1.19.2.jar

**Comment by techno-sam** [comment] 2023-07-30 22:39
Nothing in this crash log suggests that Steam 'n Rails is to blame

**Comment by ghost** [comment] 2023-08-01 11:26
> Nothing in this crash log suggests that Steam 'n Rails is to blame

Maybe you can't find anything abnormal in the log but this problem really exist.If you have patience to test and find out which mod causes it,I can report this issue to its author.

**Comment by techno-sam** [comment] 2023-08-02 00:19
Check if any of Create's ponders crash (with / without SnR present), please.

**Comment by ghost** [comment] 2023-08-02 10:20
> Check if any of Create's ponders crash (with / without SnR present), please.

I checked all the ponders of create and SnR(Yes,all the ponders).Only conductor's cap has this issue.The game crashes when this entity appears
![ZWHQ(C JEHABJK9WW( AB`G](https://github.com/Layers-of-Railways/Railway/assets/129179911/2e0e418e-2d6c-445b-9d89-ef4a0e3255fb)

**Comment by BraveCaperCat2** [comment] 2023-08-09 13:16
never seen 3-way compattibility issue before. report to the authors of JEI and Quark and maybe this problem can be fixed. (report to create too it might be create's fault as well)

**Comment by IThundxr** [comment] 2023-09-12 11:01
Does this still occur?

**Comment by ghost** [comment] 2023-09-13 23:55
> Does this still occur?

Yes.It occurs on Steam&Rails1.5.1

**Comment by IThundxr** [comment] 2023-10-02 19:33
Closing since cannot reproduce and doesn't seem like a steam n rails issue. It might be a create issue

**Closed as completed by IThundxr** 2023-10-02 19:33 UTC
Labels: type: bug, status: unable to reproduce, status: needs info, type: crash
